// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5w4_FHPs7kVlpZKbw1R40eG2A8IGoWSQ',
    appId: '1:682200561928:web:0dcec20e1346dde92a54bd',
    messagingSenderId: '682200561928',
    projectId: 'skia-coffee-login-app',
    authDomain: 'skia-coffee-login-app.firebaseapp.com',
    storageBucket: 'skia-coffee-login-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgi6wQmBJ_rzGrlthDC3uzJmi9wTe_GA',
    appId: '1:682200561928:android:0de77cc37561a28b2a54bd',
    messagingSenderId: '682200561928',
    projectId: 'skia-coffee-login-app',
    storageBucket: 'skia-coffee-login-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCuRXW2K2uvFoioc4s3APnRbGDQZKDN8',
    appId: '1:682200561928:ios:f74b1639ef5e11b12a54bd',
    messagingSenderId: '682200561928',
    projectId: 'skia-coffee-login-app',
    storageBucket: 'skia-coffee-login-app.appspot.com',
    iosBundleId: 'com.example.skiaCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCuRXW2K2uvFoioc4s3APnRbGDQZKDN8',
    appId: '1:682200561928:ios:b3ace39b8aa0c4732a54bd',
    messagingSenderId: '682200561928',
    projectId: 'skia-coffee-login-app',
    storageBucket: 'skia-coffee-login-app.appspot.com',
    iosBundleId: 'com.example.skiaCoffee.RunnerTests',
  );
}
